create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_clock_groups -asynchronous -group [get_clocks sys_clk] -group [get_clocks clk_fpga_0]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN J16 [get_ports {BC2_SEL[0]}]
set_property PACKAGE_PIN K18 [get_ports {BC2_CLK[0]}]
set_property PACKAGE_PIN H15 [get_ports {BC2_DATA[0]}]
set_property PACKAGE_PIN H20 [get_ports {BC2_DATA[1]}]
set_property PACKAGE_PIN G15 [get_ports {BC2_DATA[2]}]
set_property PACKAGE_PIN J20 [get_ports {BC2_DATA[3]}]
set_property PACKAGE_PIN N15 [get_ports {BC2_LD[0]}]
set_property PACKAGE_PIN K17 [get_ports {BC2_TRT[0]}]
set_property PACKAGE_PIN N16 [get_ports {BC2_TRR[0]}]
##g2
set_property PACKAGE_PIN V16 [get_ports {BC2_SEL[1]}]
set_property PACKAGE_PIN N17 [get_ports {BC2_CLK[1]}]
set_property PACKAGE_PIN P19 [get_ports {BC2_DATA[4]}]
set_property PACKAGE_PIN U15 [get_ports {BC2_DATA[5]}]
set_property PACKAGE_PIN N18 [get_ports {BC2_DATA[6]}]
set_property PACKAGE_PIN T15 [get_ports {BC2_DATA[7]}]
set_property PACKAGE_PIN T14 [get_ports {BC2_LD[1]}]
set_property PACKAGE_PIN P18 [get_ports {BC2_TRT[1]}]
set_property PACKAGE_PIN U14 [get_ports {BC2_TRR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports BC*]